### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'parse'

### ISSUE THREAD

**Issue by AikaJune** [IgorJanos/WikiToPdf#1]
Hello,

First, thank you for your script.

But when i'm trying to launch the python file, I have this error.
Can you help me please?

> PS C:\WikiToPdf-master\WikiToSingle> py WikiToSingle.py -s exemple.wiki -o exemple.md
> WikiToSingle.py -s <SOURCEFOLDER> -o <OUTPUTFILENAME>
> Traceback (most recent call last):
>   File "WikiToSingle.py", line 66, in <module>
>     doMain()
>   File "WikiToSingle.py", line 62, in doMain
>     return doProcess(sourceFolder, outputFilename)
>   File "WikiToSingle.py", line 17, in doProcess
>     root = WN.LoadNodeFromFolder(sourceFolder)
>   File "C:\WikiToPdf-master\WikiToSingle\Classes\WikiNode.py", line 117, in LoadNodeFromFolder
>     root = Node("Root")
>   File "C:\WikiToPdf-master\WikiToSingle\Classes\WikiNode.py", line 34, in __init__
>     self.title = escapeNodeName(title)
>   File "C:\WikiToPdf-master\WikiToSingle\Classes\WikiNode.py", line 13, in escapeNodeName
>     title = urllib.parse.unquote(title)
> AttributeError: module 'urllib' has no attribute 'parse'

My system: Windows 10 x86
Python version: Python 3.8.3

**Comment by sebaruehl** [comment]
You can replace the import statement in WikiNode.py at:

https://github.com/IgorJanos/WikiToPdf/blob/c17ca9692aeeb390fb408ca57955bef60bde5778/WikiToSingle/Classes/WikiNode.py#L10

with 

`import urllib.parse` 

to get rid of this error.
